### ISSUE TITLE
Update environment.yml

### ISSUE THREAD

**Issue by adrzewiecki** [iai-group/DialogueKit#125]
The Conda environment.yml file needs to be updated with a full set of necessary packages. So it works out of box.

Also a version has to be created for Apple silicon. With modified instructions from [here.](https://github.com/gerasimos/doc-rasa-on-m1) This also needs to be added to the README and a page in the wiki for Apple silicon users that want to use DialogueKit.

**Comment by NoB0** [comment]
Should we close this issue as the user can install the necessary packages using pip and requirements.txt file?

**Comment by kbalog** [comment]
Yes.
