### ISSUE TITLE
Check if custom comparison methods may be dropped with Python 3.9 update

### ISSUE THREAD

**Issue by kbalog** [iai-group/DialogueKit#171]
See, e.g., __eq__ in core/utterance.py

The __hash__ methods should also be removed, if possible.

**Comment by kbalog** [comment]
Thanks! I guess the question is whether any of the simple classes may be turned to dataclasses, where fields by default should be included in `__repr__` and `__eq__`, and hashing could be simply added by `x: [type] =field(hash=True)`.

**Comment by NoB0** [comment]
Refer to issues #188 and #186
