### ISSUE TITLE
Add utterance level feedback 

### ISSUE THREAD

**Issue by IKostric** [iai-group/DialogueKit#207]
Maybe an utterance id (e.g., {user_id}_{conversation_id}_{turn_id}) and feedback (like, dislike) properties on Utterance class.

**Comment by NoB0** [comment]
I am not against the idea of the id but I am not sure where it would be necessary. 
For the feedback, I wonder if it can be considered as an annotation, hence belongs more to the class `AnnotatedUtterance`.

**Comment by kbalog** [comment]
ID on the utterances is useful, e.g., if we want to save/load data on the utterance level. Consider adding a dash between the components.

+1 to Weronika's response regarding feedback. This would deserve a class on its own as it's not the type of annotation that AnnotatedUtterance is meant to capture (which are system annotations). There could be a case when feedback is also included there, but then a Feedback object can be linked.

**Comment by kbalog** [comment]
@WerLaj The PR is not in line with what's been discussed above. Feedback should be a separate class (UtteranceFeedback), not a field in Utterance!

**Comment by WerLaj** [comment]
Adding _utterance_id_ is moved to a [new issue](https://github.com/iai-group/DialogueKit/issues/214).
