### ISSUE TITLE
Handling feedback on utterance level

### ISSUE THREAD

**Issue by WerLaj** [iai-group/DialogueKit#219]
We could have `self._feedbacks: List[Feedback] = []` on the dialogue level. 

Feedback may be added for all utterances in the given dialogue or none. It is added independently for a single utterance. This way it is also possible to add feedback to previous utterances, not only to the current one (useful especially if feedback is just a "like" added for a message in a web chat). 

Then we could have `add_feedback` in `Dialogue` and `register_user_feedback` in DialogueConnector.

**Comment by NoB0** [comment]
The proposed solution is aligned with the current logic. I would add that if present the feedback could added to the JSON representation of the utterance along with the intent and annotations. Something like:

```
{
    "participant": "Agent",
    "utterance": "Do you like it?",
    "intent": "Elicit",
    "feedback": 1,
}
```
