### ISSUE TITLE
Rename `SlotValueAnnotation` to `SpanAnnotation`?

### ISSUE THREAD

**Issue by IKostric** [iai-group/DialogueKit#241]
* `Annotation` is already slot-value annotation as it has fields slot and value. Therefore, `SlotValueAnnotation` is not a descriptive name of what the class does. 
 * `SlotValueAnnotation` adds start and end fields referring to the start and end index in an utterance. `SpanAnnotation` would be more descriptive of the implementation.

**Comment by kbalog** [comment]
For `Annotation`, we could use 'key' instead of 'slot' as that class would likely be used for other types of annotations that are not of a slot nature (e.g., user satisfaction).

I like the suggestion of integrating `SpanAnnotation` into `SlotValueAnnotation`.
