### ISSUE TITLE
Move all dialogue export reader functions into utils

### ISSUE THREAD

**Issue by adrzewiecki** [iai-group/DialogueKit#94]
## The problem

Currently there are multiple modules that read the dialogue export JSON files.
If we want to change the export structure we would then need to update all the different readers across DialogueKit.

## Proposed solution

All these readers should be moved into one module that reads the JSON export and creates **Dialogue** objects. This way be only have one place to update the readers.
We will have to look at the structure of the JSON export and **Dialogue** to include the same information.

**Comment by NoB0** [comment]
Done. See `utils/dialogue_reader.py`.
